### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by IronHide-tec** [snakehaihai/MCVIO_CPU_only#1]
我在尝试运行euroc数据集时，报错如下：
I0422 11:22:54.455435 14919 MCVIOestimator_node.cpp:452] Finish initialization
double free or corruption (out)
[MCVIO_estimator-2] process has died [pid 14919, exit code -6, cmd /home/user/ros_Proj/MCVIO/devel/lib/mcvio/mcvio_estimator __name:=MCVIO_estimator __log:=/home/user/.ros/log/9b457250-0057-11ef-ab83-000c295aa69b/MCVIO_estimator-2.log].
log file: /home/user/.ros/log/9b457250-0057-11ef-ab83-000c295aa69b/MCVIO_estimator-2*.log

您能给出一些建议吗？

**Comment by IronHide-tec** [comment]
我的邮箱是wubinwenyou@163.com,关于您这个开源工程有些问题请教，希望得到您的回复。

**Comment by snakehaihai** [comment]
才看到 你当前 eigen, opencv and ceres. 个是什么版本？ 我可以试一下。 我现在3.3.4   4.2  和 2.0 目前可以跑
还有你确定你更新了 yaml 里面的几个关键参数？

**Comment by IronHide-tec** [comment]
我是在Ubuntu 18 Opencv3.2 Eigen 3.3 ceres 2.0中失败了，确实是opencv 的问题，在4.2中运行正常。感谢！

---- 回复的原邮件 ----
| 发件人 | Yuan ***@***.***> |
| 发送日期 | 2024年04月26日 10:54 |
| 收件人 | snakehaihai/MCVIO_CPU_only ***@***.***> |
| 抄送人 | IronHide-tec ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [snakehaihai/MCVIO_CPU_only] 运行报错 (Issue #1) |

才看到 你当前 eigen, opencv and ceres. 个是什么版本？ 我可以试一下。 我现在3.3.4 4.2 和 2.0 目前可以跑
还有你确定你更新了 yaml 里面的几个关键参数？
