### ISSUE TITLE
Can not run with Euroc data

### ISSUE THREAD

**Issue by DuyTPresent** [snakehaihai/MCVIO_CPU_only#2]
How do I run with Euroc data? I can't run with it.

**Comment by snakehaihai** [comment]
roslaunch mcvio MCVIO_estimator.launch 
    cd src/MCVIO/launch/
    rviz -d MCVIO_VIEW.launch
    rosbag play <Your path to dataset>/<Your bag file>.bag 
    
    
    if you have detailed problem.let me know

**Comment by DuyTPresent** [comment]
When I run the Euroc data, the topic /MCVIO_estimator/cam_1/feature_image is not shown in Rviz; I only get /MCVIO_estimator/cam_0/feature_image. This makes the estimator function unable to perform the calculation.

I do as follows:
roslaunch mcvio MCVIO_euroc.launch 
rosbag play MH_03_medium.bag

i have a problem below: 
I0829 16:28:21.105520 19089 MCVIOestimator_node.cpp:418] NUM_OF_CAM:2
I0829 16:28:21.105525 19089 MCVIOestimator_node.cpp:437] cam_0
I0829 16:28:21.105543 19089 MCVIOestimator_node.cpp:438] EXT_R: 
00.0148655 0-0.999881 00.0041403
000.999557 00.0149672 00.0257155
-0.0257744 0.00375619 000.999661
I0829 16:28:21.105561 19089 MCVIOestimator_node.cpp:440] EXT_T: 
-0.0216401
0-0.064677
0.00981073
I0829 16:28:21.105568 19089 MCVIOestimator_node.cpp:437] cam_1
I0829 16:28:21.105571 19089 MCVIOestimator_node.cpp:438] EXT_R: 
00.0125553 0-0.999755 00.0182238
000.999599 00.0130119 00.0251588
-0.0253898 00.0179006 000.999517
I0829 16:28:21.105584 19089 MCVIOestimator_node.cpp:440] EXT_T: 
-0.0198436
00.0453689
0.00786212
I0829 16:28:21.105612 19089 MCVIOestimator.cpp:58] Clear state
I0829 16:28:21.105615 19089 MCVIOestimator.cpp:64] Clear Ps, Vs, As
I0829 16:28:21.105618 19089 MCVIOestimator.cpp:86] Clear local window frame
I0829 16:28:21.105639 19089 MCVIOfeature_manager.cpp:30] Feature Manager clear state
I0829 16:28:21.105643 19089 MCVIOestimator.cpp:29] estimator init begins
I0829 16:28:21.105646 19089 MCVIOestimator.cpp:39] Estimator set parameter
[ WARN] [1724916501.105661243]: waiting for image and imu...
I0829 16:28:21.105669 19089 MCVIOestimator_node.cpp:450] Register publishers
I0829 16:28:21.110828 19089 MCVIOestimator_node.cpp:452] Finish initialization
double free or corruption (fasttop)
[MCVIO_estimator-2] process has died [pid 19089, exit code -6, cmd /home/duy/MCVIO_novpi_ws/devel/lib/mcvio/mcvio_estimator __name:=MCVIO_estimator __log:=/home/duy/.ros/log/4440dcec-65d8-11ef-a00a-93ba5cd2b0e9/MCVIO_estimator-2.log].
log file: /home/duy/.ros/log/4440dcec-65d8-11ef-a00a-93ba5cd2b0e9/MCVIO_estimator-2*.log
![problem](https://github.com/user-attachments/assets/8981faf3-8aa6-4c1c-b1ec-72b92fa3c9eb)

**Comment by snakehaihai** [comment]
Hi, I`ve tried to run it again on my PC, and I didn't encounter any issues. 

Upon closer inspection of your error, it shows.

double free or corruption (fasttop)

This is a hard-to-debug error as it often could be related to library version or hardware issues. 

MC VIO is implemented on top of vins fusion, so  there is a similar error poped in qingtong`s repo   https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/issues/85

Can you please try to see if it is the same pointer that giving out the issue?

**Comment by DuyTPresent** [comment]
Thank you for your response. 
I fixed this problem. 
But I have a question about this source. Have you tried to run with 4 cameras?

**Comment by snakehaihai** [comment]
Yes, we did.

**Comment by DuyTPresent** [comment]
Thank you for your response. 
Can you share with me the dataset to run 4 cameras and file yaml configuration?
